package com.pdp.enums;

public enum UserState {
    LANGUAGE,
    SHARING_PHOTO,
    SHARING_DOCUMENT,
    SHARING_AUDIO,
    ENTERING_NAME,
    ENTERING_AGE,
    ENTERING_EMAIL,
    SHARING_PHONE,
    SHARING_LOCATION,
    ENTERING_PASSWORD_FROM_MAIL
}
