package com.pdp.entity;

public enum UserState {
    START,
    LOGIN,
    PASSWORD,
    ADMIN_MENU,
    USER_MENU,
    ADD_PRODUCT,
    ADD_PRODUCT_NAME,
    ADD_PRODUCT_PRICE,
    ADD_PRODUCT_QUANTITY,
    ADD_PRODUCT_PHOTO,
    SHOW_USERS,
    SHOW_ORDERS,
    SHOW_PRODUCTS,
    CHOOSE_PRODUCT,
    SHOW_PRODUCT,
    SETTINGS
}
