package uz.pdp.entity;

public enum UserState {
    START,
    USER_MENU,
    ADD_BOOK_NAME,
    ADD_BOOK_PRICE,
    ADD_BOOK_QUANTITY,
    ADD_BOOK_PHOTO,
    ADD_BOOK_DOCUMENT,
    SHOW_BOOK_FOR_ADMIN,
    SHOWING_BOOK_FOR_ADMIN, SHOW_ORDER_FOR_ADMIN, SHOWING_ORDER_FOR_ADMIN, SHOW_BOOK_FOR_USER, SHOW_ORDER_FOR_USER, SHOWING_BOOK_FOR_USER, CHOOSE_BOOK_FOR_USER, SHOWING_ORDER_FOR_USER, ADMIN_MENU
}
