package uz.pdp.entity;

public enum UserState {
    START,
    USER_MENU,
    CHECK_HOMEWORK,
    GIVE_BALL,
    GIVE_ADMIN_DESCRIPTION,
    GIVE_ADMIN_FEEDBACK,
    SHOW_OLD_HOMEWORK,
    SEND_HOMEWORK_DESCRIPTION,
    SEND_HOMEWORK_ZIP_FILE,
    SHOW_OLD_HOMEWORK_FOR_USER,
    ADMIN_MENU
}
